defaults:
  - override hydra/launcher: basic

hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}

# 1. Параметры для стадии 'prepare' (из dvc.yaml)
prepare:
  img_size: [640, 640]
  augmentations: true

# 2. Параметры для стадии 'train' (из dvc.yaml)
training:
  max_epochs: 50
  batch_size: 16
  learning_rate: 0.001

# 3. Параметры модели (из dvc.yaml)
model:
  architecture: "retinanet"
  num_classes: 5
